[program:ccy-agent]
command=/opt/ccy/bin/ccy-agent -config /opt/ccy/config/agent.json
directory=/opt/ccy
user=root
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/ccy-agent.err.log
stdout_logfile=/var/log/ccy-agent.out.log
user=root
